# Funding model platforms for Baumaster.at / GENESIS

github: [Alvoradozerouno]
patreon: Alvoradozerouno
open_collective: Baumaster
ko_fi: Alvoradozerouno
custom: 
  - 'https://genesis-at.com/sponsor'
  - 'https://github.com/Alvoradozerouno/Baumaster.at/.github/INVESTORS.md'
